[alias]
r = "run -p lips-embedded --target thumbv7em-none-eabihf"
t = "test -p lips-lang"
repl = "run -p lips-repl"

[target.thumbv7em-none-eabihf]
rustflags = [
    "-C", "link-arg=-Tlink.x",
]
runner = "probe-rs run --chip nrf52833_xxAA --probe 0d28:0204"
